spring:
  application:
    name: mv-consumer-feign
  cloud:
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 192.168.66.128
    port: 5672
    username: admin
    password: 123456    
server:
  port: 10005
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@127.0.0.1:10001/eureka/
feign:
  hystrix:
    enabled: true
management:
  security:
    enabled: false
order:
  number: the fucking man!!!!!!!!!888888888888888